name: Generate Snake Animation

on:
  push:
    branches:
      - main   # Change this to your default branch if different

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate contribution snake animation
        uses: Platane/snk@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_path: output/snake.svg   # Saves the animation here

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/snake.svg
          git commit -m "Update contribution snake animation" || echo "No changes to commit"
          git push
